name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd src
        GOOS=linux GOARCH=amd64 go build -v -o ../build/api main.go
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: api
        path: build/api

    - name: Test
      run: |
        cd src
        go test -v ./...
      
    #- name: Publish to Azure
    #  run: func azure functionapp publish gowxapi --custom
    
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: api
        path: .
        
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.6
      with:
        # Name of the Azure Function App
        app-name: gowxapi
        # Path to package or folder. *.zip or a folder to deploy
        package: api
        publish-profile: <publishData><publishProfile profileName="gowxapi - Web Deploy" publishMethod="MSDeploy" publishUrl="gowxapi.scm.azurewebsites.net:443" msdeploySite="gowxapi" userName="$gowxapi" userPWD="oFtAlz2jfWgR4qm7ntwHGjeJldbkzQaovRMlN7czZM9ajFnD7WXqENEbc4mo" destinationAppUrl="http://gowxapi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="gowxapi - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-077.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="gowxapi\$gowxapi" userPWD="oFtAlz2jfWgR4qm7ntwHGjeJldbkzQaovRMlN7czZM9ajFnD7WXqENEbc4mo" destinationAppUrl="http://gowxapi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="gowxapi - Zip Deploy" publishMethod="ZipDeploy" publishUrl="gowxapi.scm.azurewebsites.net:443" userName="$gowxapi" userPWD="oFtAlz2jfWgR4qm7ntwHGjeJldbkzQaovRMlN7czZM9ajFnD7WXqENEbc4mo" destinationAppUrl="http://gowxapi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="gowxapi - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-077dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="gowxapi\$gowxapi" userPWD="oFtAlz2jfWgR4qm7ntwHGjeJldbkzQaovRMlN7czZM9ajFnD7WXqENEbc4mo" destinationAppUrl="http://gowxapi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
