name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  OS: 'linux'
  ARCH: 'amd64'
  BUILD_OUTPUT_PATH: 'build'
  ARTIFACT_NAME: 'api'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd src
        GOOS=${{ env.OS }} GOARCH=${{ env.ARCH }} go build -v -o ../${{ env.BUILD_OUTPUT_PATH }}/${{ env.ARTIFACT_NAME }} main.go
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.BUILD_OUTPUT_PATH }}/${{ env.ARTIFACT_NAME }}

    - name: Test
      run: |
        cd src
        go test -v ./...
    
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.6
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}

    - name: Log out of Azure
      run: |
        az logout

