name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd src
        GOOS=linux GOARCH=amd64 go build -v -o ../build/api main.go
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: api
        path: build/api

    - name: Test
      run: |
        cd src
        go test -v ./...
      
    #- name: Publish to Azure
    #  run: func azure functionapp publish gowxapi --custom
    
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: api
    
    - name: Print location
      run: ls
        
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.6
      with:
        # Name of the Azure Function App
        app-name: gowxapi
        # Path to package or folder. *.zip or a folder to deploy
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

